name: Automated API Tests – Lab6 N15

on: [push]

jobs:
  test-microservices:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Docker Compose
        run: docker compose up -d --build

      - name: Wait for services to be ready
        run: sleep 15

      - name: Install Node.js and Newman
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: newman run collection.json --reporters cli
